version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - gcis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./eg/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./eg/docker/ssl:/etc/certificates
  gcis:
    image: gcis:small
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=gcisops
      - MOJO_MODE=development
    volumes:
      - ./Tuba.conf:/home/gcis/Tuba.conf

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=gcisops
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d
