---
abstract: 'The Useful Backend API'
author:
  - unknown
build_requires:
  Module::Build::Mojolicious: '0'
  Mojolicious::Plugin::InstallablePaths: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
  Module::Build::Database: '0'
  Module::Build::Mojolicious: '0'
  Mojolicious::Plugin::InstallablePaths: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tuba
provides:
  Tuba:
    file: lib/Tuba.pm
    version: '1.38'
  Tuba::Activity:
    file: lib/Tuba/Activity.pm
  Tuba::Array:
    file: lib/Tuba/Array.pm
  Tuba::Article:
    file: lib/Tuba/Article.pm
  Tuba::Auth:
    file: lib/Tuba/Auth.pm
  Tuba::Book:
    file: lib/Tuba/Book.pm
  Tuba::Chapter:
    file: lib/Tuba/Chapter.pm
  Tuba::Contributor:
    file: lib/Tuba/Contributor.pm
  Tuba::Controller:
    file: lib/Tuba/Controller.pm
  Tuba::Converter:
    file: lib/Tuba/Converter.pm
  Tuba::DB:
    file: lib/Tuba/DB.pm
  Tuba::DB::Object:
    file: lib/Tuba/DB/Object.pm
  Tuba::DB::Object::Activity:
    file: lib/Tuba/DB/Mixin/Object/Activity.pm
  Tuba::DB::Object::Array:
    file: lib/Tuba/DB/Mixin/Object/Array.pm
  Tuba::DB::Object::Article:
    file: lib/Tuba/DB/Mixin/Object/Article.pm
  Tuba::DB::Object::Book:
    file: lib/Tuba/DB/Mixin/Object/Book.pm
  Tuba::DB::Object::Chapter:
    file: lib/Tuba/DB/Mixin/Object/Chapter.pm
  Tuba::DB::Object::Chapter::Manager:
    file: lib/Tuba/DB/Mixin/Object/Chapter/Manager.pm
  Tuba::DB::Object::Contributor:
    file: lib/Tuba/DB/Mixin/Object/Contributor.pm
  Tuba::DB::Object::ConventionManager:
    file: lib/Tuba/DB/Object/ConventionManager.pm
  Tuba::DB::Object::Country:
    file: lib/Tuba/DB/Mixin/Object/Country.pm
  Tuba::DB::Object::Exterm:
    file: lib/Tuba/DB/Mixin/Object/Exterm.pm
  Tuba::DB::Object::Figure:
    file: lib/Tuba/DB/Mixin/Object/Figure.pm
  Tuba::DB::Object::Figure::Manager:
    file: lib/Tuba/DB/Mixin/Object/Figure/Manager.pm
  Tuba::DB::Object::File:
    file: lib/Tuba/DB/Mixin/Object/File.pm
  Tuba::DB::Object::Finding:
    file: lib/Tuba/DB/Mixin/Object/Finding.pm
  Tuba::DB::Object::Finding::Manager:
    file: lib/Tuba/DB/Mixin/Object/Finding/Manager.pm
  Tuba::DB::Object::GcmdKeyword:
    file: lib/Tuba/DB/Mixin/Object/GcmdKeyword.pm
  Tuba::DB::Object::Generic:
    file: lib/Tuba/DB/Mixin/Object/Generic.pm
  Tuba::DB::Object::Generic::Manager:
    file: lib/Tuba/DB/Mixin/Object/Generic/Manager.pm
  Tuba::DB::Object::Image:
    file: lib/Tuba/DB/Mixin/Object/Image.pm
  Tuba::DB::Object::Instrument:
    file: lib/Tuba/DB/Mixin/Object/Instrument.pm
  Tuba::DB::Object::Journal:
    file: lib/Tuba/DB/Mixin/Object/Journal.pm
  Tuba::DB::Object::Lexicon:
    file: lib/Tuba/DB/Mixin/Object/Lexicon.pm
  Tuba::DB::Object::Manager:
    file: lib/Tuba/DB/Object/Manager.pm
  Tuba::DB::Object::Metadata:
    file: lib/Tuba/DB/Object/Metadata.pm
  Tuba::DB::Object::Metadata::Column::ISSN:
    file: lib/Tuba/DB/Object/Metadata/Column/ISSN.pm
  Tuba::DB::Object::Methodology:
    file: lib/Tuba/DB/Mixin/Object/Methodology.pm
  Tuba::DB::Object::ModelRun:
    file: lib/Tuba/DB/Mixin/Object/ModelRun.pm
  Tuba::DB::Object::Organization:
    file: lib/Tuba/DB/Mixin/Object/Organization.pm
  Tuba::DB::Object::Person:
    file: lib/Tuba/DB/Mixin/Object/Person.pm
  Tuba::DB::Object::Person::Manager:
    file: lib/Tuba/DB/Mixin/Object/Person/Manager.pm
  Tuba::DB::Object::Publication:
    file: lib/Tuba/DB/Mixin/Object/Publication.pm
  Tuba::DB::Object::PublicationContributorMap:
    file: lib/Tuba/DB/Mixin/Object/PublicationContributorMap.pm
  Tuba::DB::Object::PublicationMap:
    file: lib/Tuba/DB/Mixin/Object/PublicationMap.pm
  Tuba::DB::Object::Reference:
    file: lib/Tuba/DB/Mixin/Object/Reference.pm
  Tuba::DB::Object::Reference::Manager:
    file: lib/Tuba/DB/Mixin/Object/Reference/Manager.pm
  Tuba::DB::Object::Report:
    file: lib/Tuba/DB/Mixin/Object/Report.pm
  Tuba::DB::Object::Report::Manager:
    file: lib/Tuba/DB/Mixin/Object/Report/Manager.pm
  Tuba::DB::Object::RoleType:
    file: lib/Tuba/DB/Mixin/Object/RoleType.pm
  Tuba::DB::Object::Table:
    file: lib/Tuba/DB/Mixin/Object/Table.pm
  Tuba::DB::Object::Table::Manager:
    file: lib/Tuba/DB/Mixin/Object/Table/Manager.pm
  Tuba::DB::Object::Webpage:
    file: lib/Tuba/DB/Mixin/Object/Webpage.pm
  Tuba::DB::Objects:
    file: lib/Tuba/DB/Objects.pm
  Tuba::Dataset:
    file: lib/Tuba/Dataset.pm
  Tuba::Doc:
    file: lib/Tuba/Doc.pm
  Tuba::DocManager:
    file: lib/Tuba/DocManager.pm
  Tuba::Exterm:
    file: lib/Tuba/Exterm.pm
  Tuba::Figure:
    file: lib/Tuba/Figure.pm
  Tuba::File:
    file: lib/Tuba/File.pm
  Tuba::Finding:
    file: lib/Tuba/Finding.pm
  Tuba::GcmdKeyword:
    file: lib/Tuba/GcmdKeyword.pm
  Tuba::Generic:
    file: lib/Tuba/Generic.pm
  Tuba::Image:
    file: lib/Tuba/Image.pm
  Tuba::Instrument:
    file: lib/Tuba/Instrument.pm
  Tuba::InstrumentInstance:
    file: lib/Tuba/InstrumentInstance.pm
  Tuba::Journal:
    file: lib/Tuba/Journal.pm
  Tuba::Lexicon:
    file: lib/Tuba/Lexicon.pm
  Tuba::Log:
    file: lib/Tuba/Log.pm
  Tuba::Model:
    file: lib/Tuba/Model.pm
  Tuba::ModelRun:
    file: lib/Tuba/ModelRun.pm
  Tuba::Organization:
    file: lib/Tuba/Organization.pm
  Tuba::Person:
    file: lib/Tuba/Person.pm
  Tuba::Platform:
    file: lib/Tuba/Platform.pm
  Tuba::Plugin::Auth:
    file: lib/Tuba/Plugin/Auth.pm
  Tuba::Plugin::Db:
    file: lib/Tuba/Plugin/Db.pm
  Tuba::Plugin::TubaHelpers:
    file: lib/Tuba/Plugin/TubaHelpers.pm
  Tuba::Project:
    file: lib/Tuba/Project.pm
  Tuba::Publication:
    file: lib/Tuba/Publication.pm
  Tuba::Reference:
    file: lib/Tuba/Reference.pm
  Tuba::Region:
    file: lib/Tuba/Region.pm
  Tuba::Report:
    file: lib/Tuba/Report.pm
  Tuba::RoleType:
    file: lib/Tuba/RoleType.pm
  Tuba::RouteDoc:
    file: lib/Tuba/RouteDoc.pm
  Tuba::RouteParam:
    file: lib/Tuba/RouteParam.pm
  Tuba::Scenario:
    file: lib/Tuba/Scenario.pm
  Tuba::Search:
    file: lib/Tuba/Search.pm
  Tuba::Table:
    file: lib/Tuba/Table.pm
  Tuba::Util:
    file: lib/Tuba/Util.pm
  Tuba::Webpage:
    file: lib/Tuba/Webpage.pm
requires:
  Algorithm::Permute: '0'
  Crypt::OpenSSL::RSA: '0'
  DBD::Pg: '3.003'
  DBIx::Connector: '0'
  DBIx::Custom: '0'
  DBIx::Simple: '0'
  Data::Rmap: '0'
  Date::Parse: '0'
  DateTime::Format::Human::Duration: '0'
  Digest::SHA1: '0'
  File::ShareDir: '1.00'
  Hash::Flatten: '0'
  IO::Socket::SSL: '2'
  JSON::WebToken: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  Lingua::EN::Inflect: '0'
  Mojolicious: '6.08'
  Mojolicious::Plugin::InstallablePaths: '0'
  Mojolicious::Plugin::YamlConfig: '0'
  Number::Bytes::Human: '0'
  Number::Format: '0'
  Path::Class: '0'
  Pg::hstore: '0'
  RDF::Query: '0'
  RDF::Trine: '0'
  Rose::DB: '0.772'
  Rose::DB::Object: '0'
  SQL::Abstract: '0'
  SQL::Interp: '0'
  Scalar::Util: '0'
  Sort::Key: '0'
  String::Diff: '0'
  Swagger2: '0'
  Text::CSV_XS: '0'
  Text::Format: '0'
  Time::Duration: '0'
  URI::Find: '0'
  UUID::Tiny: '0'
  YAML: '0'
  YAML::Syck: '0'
  YAML::XS: '0'
version: '1.38'
