#!/bin/sh -e

cd `dirname $0`
export PERLBREW_ROOT=/opt/perl5
export PERLBREW_HOME=/opt/perl5/common
export MOJO_LOG_LEVEL=debug
export MOJO_MODE=production
source $PERLBREW_ROOT/etc/bashrc
hypnotoad ./Tuba

