/* #  identifier                | A globally unique identifier for this activity. */
/* # data_usage                 | A description of the way in which input data were used for this activity. */
/* # methodology                | A detailed description of the procedure. */
/* # start_time                 | The time at which this activity began. */
/* # end_time                   | The time at which this activity ended. */
/* # duration                   | The amount of time taken for this activity. */
/* # computing_environment      | Operating systems and versions used to perform this activity */
/* # output_artifacts           | Files/data products generated by this activity. */
/* # software                   | Primary software (with version) used. */
/* # visualization_software     | Primary visualization software used. */
/* # notes                      | Other information about this activity which might be useful for traceability or reproducability. */
/* #COMMENT ON COLUMN activity.duration IS 'DEPRECATED - use Contributor relationship, role Publisher, to the publisher Organization'; */
