#!!usr/bin/env perl

use lib '../../raw/lib';
use lib '../lib';

use Data::Dumper;
use Tuba::DB::Objects qw/-nicknames/;
use Goog;

use strict;
use warnings;

Files->delete_objects(all => 1);
Images->delete_objects(all => 1);
Figures->delete_objects(all => 1);
Chapters->delete_objects(all => 1);
Reports->delete_objects(all => 1);

my $goog = Goog->new(datafile => q[/var/local/projects/raw/data/goog/goog.json])->load;

# Report
my $report = Report->new(
    identifier => "nca3",
    title      => "National Climate Assessment number three",
);
$report->save or die $report->error;

# Chapters
for my $row ($goog->hashrefs(q[nca3draft.canonicalURIs.chapters],'Sheet 1')) {
    print Dumper($row);
    my $ch = Chapter->new(
        report     => $report->identifier,
        title      => $row->{q[chapter-long-name]},
        identifier => $row->{q[identifier]},
    )->save;
}




